fullnameOverride: terrarium
organizations_service:
  replicas: 1
  image:
    repository: ghcr.io/terrariumcloud/terrarium-organizations
    tag: latest
    pullPolicy: Always
modules_service:
  replicas: 1
  bucket_name: "terrarium-dev"
  image:
    repository: ghcr.io/terrariumcloud/terrarium-modules
    tag: latest
    pullPolicy: Always