apiVersion: v1
kind: Secret
metadata:
    name: {{ include "terrarium.fullname" . }}-regcred
    namespace: {{ include "terrarium.fullname" . }}
data:
  .dockerconfigjson: {{ .Values.imagePullSecret }}
type: kubernetes.io/dockerconfigjson
